---
title: "Class 14"
output: html_document
---

## Last day with sonnets

We might do functions today, maybe not.

Types vs Token distinction
Names in a table are the types, what are being counted are tokens.

Next month we will work on steming words - mapping multiple tenses to one type.

TTR - Type Token Ratio
Ratio of unique word types and total number of tokens
divide types by tokens and multiply by 100 to talk in percentages.
Lower TTR indicates less variety

Mean Word Frequency (MWF)
Number of times any word is used on average (number of tokens divided by types)
MWF indicates the rate at which word types are reused.
A higher MWF may indicate less variety.

Sonnets
14 lines
Iambic pentameter
Up to 140 words in a sonnet

Talking about the Types and Tokens of outlier sonnets

"I cannot hide what I am"
"I am not what I am"

```{r }
john <- "I cannot hide what I am"
length(john)
john <- unlist(strsplit(john, " "))
length(john)
length(table(john)) #Table is only 5 long because of only 5 types.

john <- "I am not what I am "
iago <- unlist(strsplit(john, " "))
length(iago)
length(table(iago))

```

## Gertrude Stein - Sacred Emily

Rose is a rose is a rose is a rose

Philosophy - There are only tokens in the world
Each of the words are different

Depends on the extent of detail being evaluated

Plato - types are real
Nominalists, John locke - types are not real

```{R}

stein <- "Rose is a rose is a rose is a rose"
library(stringr)
steinwords <- unlist(str_split(stein,boundary("word")))
length(table(steinwords))

steinwords <- tolower(unlist(str_split(stein,boundary("word"))))
length(table(steinwords))

sonnetrawtables.l <- readRDS("sonnetlists.RDS")[[3]]
sum(sonnetrawtables.l[[18]]) # Total number of words in sonnet 18

length(sonnetrawtables.l[[18]]) # Number of unique words

#TTR
length(sonnetrawtables.l[[18]]) / sum(sonnetrawtables.l[[18]]) * 100

# MWF
# on average, any word in our vocabulary is used 1.373494 times on average
mean(sonnetrawtables.l[[18]])

```

## Working with lots of sonnets at once.

```{R}
sapply(sonnetrawtables.l,sum)
sonnet.tokens <- do.call(cbind, lapply(sonnetrawtables.l,sum))
sonnet.vocab <- do.call(cbind, lapply(sonnetrawtables.l,length))
sonnet.mean <- do.call(cbind, lapply(sonnetrawtables.l, mean))

which.max(sapply(sonnetrawtables.l, length)) # s(first) sonnet with the most unique words
max(sapply(sonnetrawtables.l, length))

sort(sapply(sonnetrawtables.l, length))

```

## Question 2 on the homework related
All ttrs at once

```{R}

sonnet.usage <- rbind(sonnet.tokens, sonnet.vocab, sonnet.mean)
row.names(sonnet.usage) <- c("tokens", "vocab", "MWF")
View(t(sonnet.usage))

# ttr all at once
sonnet.usage["vocab"]
sonnet.usage["tokens"]

# ttr is tokens divided by vocab

ttr <- sonnet.usage[2,]/sonnet.usage[1,]*100
sonnet.usage <- rbind(sonnet.usage, ttr)
View(t(sonnet.usage))

unlist(sapply(sonnetrawtables.l, names), use.names = F) # a representation of vocabulary used to write the sonnets

#to get types
unique(unlist(sapply(sonnetrawtables.l, names), use.names = F)) # These are the types

sum(sapply(sonnetrawtables.l, sum)) # # of tokens
length(unique(unlist(sapply(sonnetrawtables.l, names), use.names = F))) # Types


# Making a big matrix
sonnetwords <- unique(unlist(sapply(sonnetrawtables.l, names), use.names = F))
sonnet.m <- sapply(sonnetrawtables.l, '[', sonnetwords)
View(sonnet.m)

```